### ISSUE TITLE
Cluster does not startup on vagrant

### ISSUE THREAD

**Issue by nbyl** [gravitational/quickstart#17]
When I try to start the mattermost cluster on vagrant as described in the quickstart docs, the operation will fail like this:

```
node-1: Wed Dec 19 12:59:16 UTC	Wait for system services to start on all nodes
node-1: Wed Dec 19 13:07:39 UTC	Operation failure: planet is not running yet: &{Degraded [{ 172.28.128.101 master  degraded [kube-apiserver (Get https://10.100.0.1/api/v1/componentstatuses/scheduler: dial tcp 10.100.0.1:443: connect: connection refused)]}]}
node-1: Wed Dec 19 13:07:39 UTC	Installation failed in 9m35.590975162s, check /var/log/telekube-install.log for details
```

Any hints where to search? I've attached the [logfile](https://github.com/gravitational/quickstart/files/2694961/telekube-install.log).

**Comment by benarent** [comment]
Hi @nbyl, sorry for the delay, but better late than never!

It looks like the master server couldn't connect, this could be connectivity issue between the masters nodes and the clients.  You can use `gravity status` to get an overview of how the cluster is working. 

```
Wed Dec 19 13:07:39 UTC [ERROR] [node-1] Phase /wait execution failed: planet is not running yet: &{Degraded [{ 172.28.128.101 master  degraded [kube-apiserver (Get https://10.100.0.1/```
