### ISSUE TITLE
Does this work with the current release?

### ISSUE THREAD

**Issue by jayunit100** [gravitational/quickstart#20]
This look like it is no longer supported :( 

```
 ⚡ root@xyz /home/centos/gravity/quickstart   master  tele build -o mattermost.tar mattermost/resources/app.yaml
* [1/6] Selecting base image version
        Will use base image version 5.2.5 set in manifest
* [1/6] Build aborted after now
[ERROR]: Version of this tele binary (5.5.8) is not compatible with the base image version specified in the manifest (5.2.5).
```

**Comment by hdhruna** [comment]
Probably try changing the runtime version here to your tele binary version
https://github.com/gravitational/quickstart/blob/080dc6646af7e648fbf7942b7b32f9f3f9cc4d0f/mattermost/resources/app.yaml#L86

**Comment by benarent** [comment]
Thanks for replying @hdhruna. That's the correct answer. Let me know if anything else comes up.
