### ISSUE TITLE
Bump Mattermost to latest version. 

### ISSUE THREAD

**Issue by benarent** [gravitational/quickstart#25]
We currently build a 2yr old version of Mattermost https://github.com/gravitational/quickstart/blob/master/mattermost/worker/Dockerfile#L8 

Mattermost has improved a lot, it might be worth bumping to 5.10 or greater.

**Comment by webvictim** [comment]
s/mark/most/g 😁

**Comment by benarent** [comment]
ha, must of had the data enrichment software on my mind.
